/** Official TCG set abbreviations → TCGdex set ids. Seeded from api.tcgdex.net set details. */
export const SET_CODES: Record<string, string> = {
  MCD11: "2011bw",
  MCD12: "2012bw",
  MCD14: "2014xy",
  MCD15: "2015xy",
  MCD16: "2016xy",
  MCD17: "2017sm",
  MCD18: "2018sm",
  MCD19: "2019sm",
  MCD21: "2021swsh",
  MCD22: "2022swsh",
  MCD23: "2023sv",
  MCD24: "2024sv",
  BS: "base1",
  JU: "base2",
  FO: "base3",
  B2: "base4",
  RO: "base5",
  BLW: "bw1",
  PLB: "bw10",
  LTR: "bw11",
  EP: "bw2",
  NVI: "bw3",
  NXD: "bw4",
  DEX: "bw5",
  DRX: "bw6",
  BCR: "bw7",
  PLS: "bw8",
  PLF: "bw9",
  BWP: "bwp",
  CEL: "cel25",
  COL: "col1",
  DCR: "dc1",
  DET: "det1",
  DP: "dp1",
  MT: "dp2",
  SW: "dp3",
  GE: "dp4",
  MD: "dp5",
  LA: "dp6",
  SF: "dp7",
  DRV: "dv1",
  EX: "ecard1",
  AQ: "ecard2",
  SK: "ecard3",
  RS: "ex1",
  UF: "ex10",
  DS: "ex11",
  LM: "ex12",
  HP: "ex13",
  CG: "ex14",
  DF: "ex15",
  PK: "ex16",
  SS: "ex2",
  DR: "ex3",
  MA: "ex4",
  HL: "ex5",
  RG: "ex6",
  TR: "ex7",
  DX: "ex8",
  EM: "ex9",
  FUT20: "fut2020",
  GEN: "g1",
  G1: "gym1",
  G2: "gym2",
  HS: "hgss1",
  UL: "hgss2",
  UND: "hgss3",
  TRI: "hgss4",
  LC: "lc",
  MEG: "me01",
  PFL: "me02",
  ASC: "me02.5",
  POR: "me03",
  CRI: "me04",
  PBL: "me05",
  MEE: "mee",
  MEP: "mep",
  MFB: "mfb",
  N1: "neo1",
  N2: "neo2",
  N3: "neo3",
  N4: "neo4",
  PL: "pl1",
  RR: "pl2",
  SV: "pl3",
  AR: "pl4",
  P1: "pop1",
  P2: "pop2",
  P3: "pop3",
  P4: "pop4",
  P5: "pop5",
  P6: "pop6",
  P7: "pop7",
  P8: "pop8",
  P9: "pop9",
  RM: "ru1",
  SI: "si1",
  SUM: "sm1",
  UNB: "sm10",
  UNM: "sm11",
  HIF: "sm115",
  CEC: "sm12",
  GRI: "sm2",
  BUS: "sm3",
  SLG: "sm3.5",
  CIN: "sm4",
  UPR: "sm5",
  FLI: "sm6",
  CES: "sm7",
  DRM: "sm7.5",
  LOT: "sm8",
  TEU: "sm9",
  SMP: "smp",
  SVI: "sv01",
  PAL: "sv02",
  OBF: "sv03",
  MEW: "sv03.5",
  PAR: "sv04",
  PAF: "sv04.5",
  TEF: "sv05",
  TWM: "sv06",
  SFA: "sv06.5",
  SCR: "sv07",
  SSP: "sv08",
  PRE: "sv08.5",
  JTG: "sv09",
  DRI: "sv10",
  BLK: "sv10.5b",
  WHT: "sv10.5w",
  SVE: "sve",
  SVP: "svp",
  SSH: "swsh1",
  ASR: "swsh10",
  PGO: "swsh10.5",
  LOR: "swsh11",
  SIT: "swsh12",
  CRZ: "swsh12.5",
  RCL: "swsh2",
  DAA: "swsh3",
  CPA: "swsh3.5",
  VIV: "swsh4",
  SHF: "swsh4.5",
  BST: "swsh5",
  CRE: "swsh6",
  EVS: "swsh7",
  FST: "swsh8",
  BRS: "swsh9",
  KSS: "xy0",
  XY: "xy1",
  FCO: "xy10",
  STS: "xy11",
  EVO: "xy12",
  FLF: "xy2",
  FFI: "xy3",
  PHF: "xy4",
  PRC: "xy5",
  ROS: "xy6",
  AOR: "xy7",
  BKT: "xy8",
  BKP: "xy9",
  XYP: "xyp",
};

const CODE_SWAPS: Record<string, string> = {
  "0": "O",
  "1": "I",
  "4": "A",
  "5": "S",
  "8": "B",
};

const extraCodes = new Map<string, string>();

export function setIdForCode(code: string | null | undefined): string | undefined {
  if (!code) return undefined;
  const key = code.toUpperCase().replace(/[^A-Z0-9]/g, "");
  return extraCodes.get(key) ?? SET_CODES[key];
}

export function rememberSetCode(code: string, setId: string) {
  extraCodes.set(code.toUpperCase().replace(/[^A-Z0-9]/g, ""), setId);
}

export function codeVariants(raw: string) {
  const upper = raw.toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (upper.length < 2 || upper.length > 6) return [];
  const variants = new Set<string>([upper]);
  let swapped = "";
  for (const char of upper) swapped += CODE_SWAPS[char] ?? char;
  if (swapped !== upper) variants.add(swapped);
  return [...variants];
}

export function knownCodesByLength() {
  return Object.keys(SET_CODES).sort((a, b) => b.length - a.length);
}
